version: '3'
services:
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    volumes:
      - /project/docker-compose/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    privileged: true    #环境变量
