version: '3'
services:
  kibana:
    image: kibana:7.12.0
    container_name: kibana
    privileged: true
    # environment:
    #   SERVER_NAME: 127.0.0.1
    #   ELASTICSEARCH_HOSTS: '["http://127.0.0.1:9200"]'
    volumes:
      - /project/docker-compose/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elknet


networks:
  elknet:
    driver: bridge  