version: '3'
services:
  opengauss:
    image: enmotech/opengauss:3.0.0
    container_name: opengauss
    environment:
      GS_PASSWORD: Enmo@123
    volumes:
      - ./data:/var/lib/opengauss/data
    ports:
      - 15432:5432