version: '3'
services:
  redis:
    image: enmotech/opengauss:3.0.0
    container_name: opengauss
    environment:
      GS_PASSWORD: root
    # volumes:
    #   - /project/docker-compose/redis/datadir:/data
    #   - /project/docker-compose/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 15432:15432