version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
     RABBITMQ_DEFAULT_VHOST: '/'
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - /project/docker-compose/rabbitmq/data/:/var/lib/rabbitmq/
      - /project/docker-compose/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672