# version: '3'
# services:
#   elasticsearch:
#     image: elasticsearch:8.2.1
#     container_name: elasticsearch
#     volumes:
#       - "/project/docker-compose/elasticsearch/data:/usr/share/elasticsearch/data"
#       - "/project/docker-compose/elasticsearch/logs:/usr/share/elasticsearch/logs"
#       - "/project/docker-compose/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
# #      - "./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options"
#     environment:                              # 设置环境变量,相当于docker run命令中的-e
#       TZ: Asia/Shanghai
#       LANG: en_US.UTF-8
#       discovery.type: single-node
#       # ES_JAVA_OPTS: "-Xmx512m -Xms512m"
#       ELASTIC_PASSWORD: "123456" # elastic账号密码
#     ports:
#       - "9200:9200"
#       - "9300:9300"

#   kibana:
#     image: kibana:8.2.1
#     container_name: kibana
#     volumes:
#       - /project/docker-compose/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
#     ports:
#       - "5601:5601"
#     depends_on:
#       - elasticsearch
#     links:
#       - elasticsearch
#     networks:
#       - es

version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.7.0  #镜像
    container_name: elasticsearch  #定义容器名称
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - /project/docker-compose/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /project/docker-compose/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200 
