version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: elasticsearch  #定义容器名称
    privileged: true
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - /project/docker-compose/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /project/docker-compose/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200 
    # networks:
    #   - elknet   
  kibana:
    image: kibana:7.12.0
    container_name: kibana
    privileged: true
    # volumes:
    #   - /project/docker-compose/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

    # networks:
    #   - elknet 

# networks:
#   elknet:
#     driver: bridge  

# 查看容器的ip地址
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' elasticsearch
      
