version: '3'
services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    # privileged: true
    ports:
      # - 80:80
      - 443:443
    volumes:
      # 映射nginx的配置文件到容器里
      - ./conf/:/etc/nginx/conf.d/
      # 日志文件
      - ./logs/:/var/log/nginx/
      # 映射nginx的静态文件到容器里
      - ./webroot/:/webroot/
      #若用到ssl，可以引入
      - ./ssl/:/ssl/
