version: '3'
services:
  jenkins:
    # restart: always
    image: jenkins/jenkins
    container_name: jenkins    
    privileged: true
    user: root
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8090:8080
      - 50000:50000
    volumes:
      - /project/docker-compose/jenkins/etc/localtime:/etc/localtime
      - /project/docker-compose/jenkins/opt/jenkins/data:/var/jenkins_home
      - /project/docker-compose/jenkins/var/run/docker.sock:/var/run/docker.sock
      - /project/docker-compose/jenkins/usr/bin/docker:/usr/bin/docker