version: '3'
services:
  # zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
  # kafka
  kafka:
    image: wurstmeister/kafka
    privileged: true
    container_name: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # 挂载 kafka 日志
      # :前面的路径是你电脑上路径 后面是kafka容器日志路径
      # - /project/docker-compose/kafka/logs:/kafka/logs
    ports:
      - '9092:9092'
    environment:
      # client 要访问的 broker 地址
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      # 通过端口连接 zookeeper
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 每个容器就是一个 broker，设置其对应的 ID
      KAFKA_BROKER_ID: 1
      # 外部网络只能获取到容器名称，在内外网络隔离情况下
      # 通过名称是无法成功访问 kafka 的
      # 因此需要通过绑定这个监听器能够让外部获取到的是 IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      # kafka 监听器，告诉外部连接者要通过什么协议访问指定主机名和端口开放的 Kafka 服务。
      KAFKA_LISTENERS: PLAINTEXT://:9092
      # Kafka默认使用-Xmx1G -Xms1G的JVM内存配置，由于服务器小，调整下启动配置
      # 这个看自己的现状做调整，如果资源充足，可以不用配置这个
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms128M'
      # 设置 kafka 日志位置
      # KAFKA_LOG_DIRS: "/kafka/logs"
      # 创建默认的Topic
      KAFKA_CREATE_TOPICS: 'testTopic:1:1'



# version: '3'
# services:
#   # zookeeper
#   zookeeper:
#     image: wurstmeister/zookeeper
#     container_name: zookeeper
#     ports:
#       - '2181:2181'
#   # kafka
#   kafka:
#     image: wurstmeister/kafka
#     privileged: true
#     container_name: kafka
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       # 挂载 kafka 日志
#       # :前面的路径是你电脑上路径 后面是kafka容器日志路径
#       # - /project/docker-compose/kafka/logs:/kafka/logs
#     ports:
#       - '9092:9092'
#     environment:
#       # client 要访问的 broker 地址
#       KAFKA_ADVERTISED_HOST_NAME: zookeeper
#       # 通过端口连接 zookeeper
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       # 每个容器就是一个 broker，设置其对应的 ID
#       KAFKA_BROKER_ID: 1
#       # 外部网络只能获取到容器名称，在内外网络隔离情况下
#       # 通过名称是无法成功访问 kafka 的
#       # 因此需要通过绑定这个监听器能够让外部获取到的是 IP
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       # kafka 监听器，告诉外部连接者要通过什么协议访问指定主机名和端口开放的 Kafka 服务。
#       KAFKA_LISTENERS: PLAINTEXT://kafka:9092
#       # Kafka默认使用-Xmx1G -Xms1G的JVM内存配置，由于服务器小，调整下启动配置
#       # 这个看自己的现状做调整，如果资源充足，可以不用配置这个
#       KAFKA_HEAP_OPTS: '-Xmx256M -Xms128M'
#       # 设置 kafka 日志位置
#       # KAFKA_LOG_DIRS: "/kafka/logs"
#       # 创建默认的Topic
#       KAFKA_CREATE_TOPICS: 'rebateTopic:1:1'
#     depends_on:
#         - zookeeper      