version: '3'
services:
  redis:
    image: redis:7.0-rc3
    container_name: redis
    volumes:
      - ./datadir:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes --requirepass "root"
    ports:
      - 6379:6379